package lexer

enum class TokenType {
    KEYWORD, IDENTIFIER, NUMBER, SYMBOL, EOF, COMMENT,
    IF, ELSE, FOR, WHILE, FUNCTION, RETURN,
    LEFT_BRACE, RIGHT_BRACE, LEFT_BRACKET, RIGHT_BRACKET,
    COMMA
}